# Generated by Django 4.2.5 on 2023-10-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_client", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saved",
            name="category",
        ),
        migrations.AddField(
            model_name="saved",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_client.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sold",
            field=models.BooleanField(),
        ),
    ]
