# Generated by Django 4.2.6 on 2023-10-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0002_remove_saved_category_saved_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.JSONField(null=True),
        ),
    ]
