# Generated by Django 4.2.6 on 2023-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0003_product_description_product_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='posted',
            field=models.DateTimeField(null=True),
        ),
    ]
