# Generated by Django 5.0.1 on 2024-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0003_remove_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
