# Generated by Django 5.0.1 on 2024-05-26 13:59

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0004_alter_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='posted',
        ),
        migrations.AddField(
            model_name='product',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 5, 26, 13, 59, 49, 652511, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
