# Generated by Django 4.2.6 on 2023-11-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0006_user_date_created_alter_category_id_alter_click_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_chat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_details',
            field=models.TextField(null=True),
        ),
    ]
