# Generated by Django 5.0.1 on 2024-05-28 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0008_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='count',
            field=models.IntegerField(default=0, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce_client.product'),
        ),
    ]
