# Generated by Django 5.0.1 on 2024-05-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0010_saved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_product', to='ecommerce_client.product'),
        ),
    ]
