# Generated by Django 5.0.1 on 2024-06-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0012_attribute_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='emoji',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
