# Generated by Django 5.0.1 on 2024-06-26 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_client', '0013_alter_category_emoji_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueOption',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('schema_friendly_id', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='emoji',
        ),
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='friendly_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='handle',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='schema_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='schema_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_client.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_client.category')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValueOptions',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_client.attribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_client.valueoption')),
            ],
        ),
    ]
